name: Customer pull-request

on:
  pull_request:
    paths:
      - 'customer/**'
      - 'shared/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn workspace @monorepo/customer test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          working-directory: customer
          start: yarn workspace @monorepo/components build, yarn start
          wait-on: 'http://localhost:3000'
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: customer-cypress-videos
          path: customer/cypress/videos

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn customer:lint
      - run: yarn workspace @monorepo/components build
      - run: yarn workspace @monorepo/customer build
