name: Planner pull-request

on:
  pull_request:
    paths:
      - 'planner/**'
      - 'shared/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn workspace @monorepo/planner test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          working-directory: planner
          start: yarn workspace @monorepo/components build, yarn start
          wait-on: 'http://localhost:4000'
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: planner-cypress-videos
          path: planner/cypress/videos

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn planner:lint
      - run: yarn workspace @monorepo/components build
      - run: yarn workspace @monorepo/planner build
