name: Build preview helpers

on:
  pull_request:
    paths:
      - 'shared/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["customer", "planner"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies 
        run: yarn install
  
      - name: Build components
        run: yarn workspace @monorepo/components build

      - name: Build ${{ matrix.app }}
        run: yarn workspace @monorepo/${{ matrix.app }} build
