name: Build preview helpers

on:
  pull_request:
    paths:
      - 'shared/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["components", "customer", "planner"]
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

      - name: Install ${{ matrix.app }}
        run: yarn install

      - name: Build ${{ matrix.app }}
        run: yarn workspace @monorepo/${{ matrix.app }} test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["customer", "planner"]
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
      - name: Install ${{ matrix.app }}
        run: yarn install

      - name: Build components
        run: yarn workspace @monorepo/components build

      - name: Build ${{ matrix.app }}
        run: yarn workspace @monorepo/${{ matrix.app }} build
