name: Build preview helpers

on:
  pull_request:
    paths:
      - 'shared/**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies 
        run: yarn install
  
  build-components:  
    needs: install
    steps:
      - name: Build components
        run: yarn workspace @monorepo/components tsc

  build-customer:  
    needs: install
    steps:
      - name: Build customer
        run: yarn workspace @monorepo/customer build

  build-planner:  
    needs: install
    steps:
      - name: Build planner
        run: yarn workspace @monorepo/planner build