name: Shared pull-request

on:
  pull_request:
    paths:
      - 'shared/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn components:lint && yarn helpers:lint
      - run: yarn workspace @monorepo/components test
